
package com.mycompany.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapInterface", targetNamespace = "http://soap.mycompany.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapInterface {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "duplicator", targetNamespace = "http://soap.mycompany.com/", className = "com.mycompany.soap.Duplicator")
    @ResponseWrapper(localName = "duplicatorResponse", targetNamespace = "http://soap.mycompany.com/", className = "com.mycompany.soap.DuplicatorResponse")
    @Action(input = "http://soap.mycompany.com/SoapInterface/duplicatorRequest", output = "http://soap.mycompany.com/SoapInterface/duplicatorResponse")
    public String duplicator(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
